language: python
- '3.5'
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
script:
- make publish
- make github
env:
  global:
    secure: ZnkxXtgITJYTJgDzzl88sbG78Jd6pkqqx6nrisQJL+YDlTI1ihx07qDjvnWWALsNWs51mhslqNqNdLjjytrMjWLg78up/WR6DUf/Y+naRfLRRf0V6FTDea7G9TQFWpUwmThyUZrpy8QRvMPfED0F1m400CZGiJzNFgGSSqefM6rST5JGXYXwMHjx8xVeUkBXgZ+Yxpey17hKDctVqAqEuhX24+2+iSfXAeDJrru2RONB+CmpXhp5ljT5o2dexgMQVQO+X9mX/sqZj1tlVgGe1R5PnpTl+E0ZsBR4beOTao8oqDT/Mov+yy8DL3CCcusEL2RXPBNpc33pOvPoUEstCnZgcjMxmN6dh2Jtfxv37B0BVkkkMTzVIFQQBTvuvDiDkC74+sPdMET4LlOlWODkNhnywTH/vlNP8OYUS25HCwB9Hu6pJ2HFfPHCi6j8Z6q8UDNrM0JekN9FtrYC6rb1r9S2vSw82vbge9uWxmdLL6ozJOdBWndNW0biBhJdksxKk3+UtgS6sA/C6DxspCnA3cU4OKXtjmsuz2XX4f9GvpTVIzGdDnuDKqss+quCam/SVvd3XbupI9Id0lXVgWdoauIRSc5HmL7GFK8Nnih9Bwj56jjxdt1Twy94JFyzUB4WxjaUu62Q4ZjPC4IYeKmA8O4JjlyWggog5llQEhEU76E=
